---
name: rule1
pack: vm_task_queue
description: Sample rule firing on vm_task_queue.event1.
enabled: true
trigger:
    type: vm_task_queue.event1
action:
    ref: vm_task_queue.action1
    parameters:
        greeting: Yo